#!/usr/bin/env bash
# CI: regenerate the bundled web render worker and keep it in git in sync with
# the source, instead of failing the build when it drifts. See issue #411.
#
# `packages/dart_pdf_editor/assets/web/pdf_render_worker.dart.js` is a
# `dart compile js` bundle that links most of the stack, so any change to
# pdf_cos / pdf_document / pdf_graphics / dart_pdf_editor can make it stale. It
# is a *declared Flutter asset* that ships inside the published pub.dev package
# and is needed for a fresh clone-and-run, so it has to stay checked in - what
# should never happen is a human having to remember to rebuild it.
#
# On a same-repo pull request this rebuilds the bundle and, if it changed,
# commits it to the PR head branch and pushes. On forks and push events (where
# a push back is not available) it falls back to the old verify-and-fail.
#
# The build runs against the checked-out tree. On a `pull_request` event
# `actions/checkout` checks out the merge ref (the PR head merged with the base
# branch), so the bundle is built from the *merged* source - this is the
# ordering constraint from #411: regenerating against the PR's old base would
# produce a bundle that goes stale again the moment it merges.
#
# Env (set by the workflow):
#   ASSET        path to the checked-in bundle (required)
#   EVENT_NAME   github.event_name
#   IS_SAME_REPO "true" when the PR head repo is this repo (not a fork)
#   HEAD_REF     github.event.pull_request.head.ref (the PR branch)
set -euo pipefail

ASSET="${ASSET:?ASSET must point at the checked-in bundle}"

TMP1="$(mktemp)"
TMP2="$(mktemp)"
trap 'rm -f "$TMP1" "$TMP2"' EXIT

build() {
  # Same compile the deploy workflows run; also the gate that catches
  # `.toJS`-conversion errors `dart analyze` misses (async message handlers).
  dart run dart_pdf_editor:build_web_worker --out "$1"
}

echo "==> Building the web render worker from the checked-out (merged) source"
build "$TMP1"

# Reproducibility: a second build must byte-match the first, confirming the
# output is not machine-dependent (stable across macOS arm64 and CI Linux x64
# on the pinned SDK). This caught a real problem on #410.
echo "==> Rebuilding to confirm the output is reproducible"
build "$TMP2"
if ! cmp -s "$TMP1" "$TMP2"; then
  echo "::error::Web render worker build is not reproducible (two builds differ)."
  exit 1
fi

if cmp -s "$TMP1" "$ASSET"; then
  echo "==> Bundled web render worker is already up to date."
  exit 0
fi

echo "==> Bundled web render worker is stale (source changed since last build)."

# Only a same-repo pull request can push the regenerated bundle back. The
# default GITHUB_TOKEN is read-only for fork PRs, and we do not auto-commit to
# main on push events.
if [ "${EVENT_NAME:-}" = "pull_request" ] && [ "${IS_SAME_REPO:-}" = "true" ]; then
  : "${HEAD_REF:?HEAD_REF must be set for a same-repo pull request}"
  echo "==> Regenerating on PR branch '$HEAD_REF' and pushing"

  # Move onto the real head branch (the build ran on the detached merge ref) so
  # the commit lands on the PR branch. `-f` discards the merge-ref working tree
  # and anything `flutter pub get` touched (e.g. pubspec.lock).
  git fetch origin "$HEAD_REF"
  git checkout -f -B "$HEAD_REF" "origin/$HEAD_REF"

  # Overlay the merged-source build onto the head branch. Committing it to head
  # alone is correct: it is byte-identical to what the tree produces once the PR
  # merges, so it will not re-stale on merge.
  cp "$TMP1" "$ASSET"

  if git diff --quiet -- "$ASSET"; then
    echo "==> Head branch copy already matches the merged-source build; nothing to commit."
    exit 0
  fi

  git config user.name "github-actions[bot]"
  git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
  git add "$ASSET"
  # A push made with the default GITHUB_TOKEN does NOT re-trigger workflows, so
  # this cannot loop. The follow-up commit therefore carries no CI run of its
  # own; the reproducible build in this run is the evidence it is correct. Swap
  # in a PAT/App token if you want the follow-up commit to re-run checks (this
  # script is idempotent - it no-ops once the bundle is fresh, so that is safe).
  git commit -m "chore(editor): rebuild the bundled web render worker

Regenerated by CI because a source change left the bundle stale. A textual
merge of two dart2js outputs is meaningless, so CI owns the regeneration.
See issue #411."
  git push origin "HEAD:$HEAD_REF"
  echo "::notice::Regenerated and pushed the bundled web render worker to $HEAD_REF."
  exit 0
fi

# Forks and push events: cannot push back, so fail with the actionable message.
echo "::error::Bundled web worker is stale; run app/tool/build_web.sh (or push from a same-repo branch so CI can regenerate it)."
exit 1
