import 'package:material_ui/material_ui.dart';

import '../../l10n/dart_pdf_editor_localizations.dart';

/// The localizations delegates to register at the root of an app that
/// hosts the editor.
///
/// ```dart
/// MaterialApp( // material_ui's
///   localizationsDelegates: PdfEditorLocalizations.delegates,
///   supportedLocales: PdfEditorLocalizations.supportedLocales,
///   ...
/// )
/// ```
///
/// The list is the editor's strings ([DartPdfEditorLocalizations.delegate])
/// plus material_ui's `GlobalMaterialLocalizations.delegates`: the
/// material_ui Material strings, cupertino_ui's Cupertino strings (which the
/// iOS and macOS text-selection menus read) and the widgets strings. Spread
/// it with your own app's delegates when you have them.
///
/// Registering it is recommended, not required: the editor's widgets supply
/// whichever of these localizations the host lacks, for the ambient locale.
///
/// [DartPdfEditorLocalizations.localizationsDelegates] is generated by
/// `flutter gen-l10n` and still lists the legacy
/// `package:flutter_localizations` delegates - the right list for a host on
/// the legacy `package:flutter/material.dart` `MaterialApp`, but not one that
/// gives a material_ui app its Material strings.
abstract final class PdfEditorLocalizations {
  /// The editor's delegate plus material_ui's (Material, Cupertino and
  /// widgets) for an app's `localizationsDelegates`.
  static const List<LocalizationsDelegate<dynamic>> delegates =
      <LocalizationsDelegate<dynamic>>[
    DartPdfEditorLocalizations.delegate,
    ...GlobalMaterialLocalizations.delegates,
  ];

  /// The locales the editor's strings are translated into.
  static const List<Locale> supportedLocales =
      DartPdfEditorLocalizations.supportedLocales;
}
