import 'package:cupertino_ui/cupertino_ui.dart'
    show CupertinoLocalizations, DefaultCupertinoLocalizations;
import 'package:flutter/foundation.dart' show SynchronousFuture;
import 'package:material_ui/material_ui.dart';

import '../../l10n/dart_pdf_editor_localizations.dart';

/// The localizations delegates to register at the root of an app that
/// hosts the editor.
///
/// ```dart
/// MaterialApp( // material_ui's
///   localizationsDelegates: PdfEditorLocalizations.delegates,
///   supportedLocales: PdfEditorLocalizations.supportedLocales,
///   ...
/// )
/// ```
///
/// The list is the editor's strings ([DartPdfEditorLocalizations.delegate])
/// plus material_ui's `GlobalMaterialLocalizations.delegates`: the
/// material_ui Material strings, cupertino_ui's Cupertino strings (which the
/// iOS and macOS text-selection menus read) and the widgets strings. Spread
/// it with your own app's delegates when you have them. For an editor locale
/// the framework has no translation of (Central Kurdish, `ckb`) it ends with
/// fallbacks: English Material and Cupertino strings, and the locale's own
/// text direction - so the host's `Localizations` resolves every type and a
/// right-to-left editor locale lays out right to left.
///
/// Registering it is recommended, not required: the editor's widgets supply
/// whichever of these localizations the host lacks, for the ambient locale.
///
/// [DartPdfEditorLocalizations.localizationsDelegates] is generated by
/// `flutter gen-l10n` and still lists the legacy
/// `package:flutter_localizations` delegates - the right list for a host on
/// the legacy `package:flutter/material.dart` `MaterialApp`, but not one that
/// gives a material_ui app its Material strings.
abstract final class PdfEditorLocalizations {
  /// The editor's delegate plus material_ui's (Material, Cupertino and
  /// widgets) for an app's `localizationsDelegates`.
  static const List<LocalizationsDelegate<dynamic>> delegates =
      <LocalizationsDelegate<dynamic>>[
    DartPdfEditorLocalizations.delegate,
    ...GlobalMaterialLocalizations.delegates,
    // after the framework's, which win wherever they have a translation
    _FallbackMaterialDelegate(),
    _FallbackCupertinoDelegate(),
    _FallbackWidgetsDelegate(),
  ];

  /// The locales the editor's strings are translated into.
  static const List<Locale> supportedLocales =
      DartPdfEditorLocalizations.supportedLocales;
}

/// Whether [locale] is an editor locale the framework does not translate -
/// the only locales the fallbacks below answer for. material_ui's Material
/// set stands for all three: the framework's Material, Cupertino and widgets
/// language sets agree on every editor locale (`package:flutter_localizations`
/// itself is off limits here - see tool/check_design_imports.dart).
bool _editorOnly(Locale locale) =>
    DartPdfEditorLocalizations.delegate.isSupported(locale) &&
    !GlobalMaterialLocalizations.delegate.isSupported(locale);

/// Editor locales written right to left that the framework's widgets
/// localizations do not know (they cover ar, fa, he, ps, sd and ur).
const _rtlLanguages = {'ckb'};

class _FallbackMaterialDelegate
    extends LocalizationsDelegate<MaterialLocalizations> {
  const _FallbackMaterialDelegate();

  @override
  bool isSupported(Locale locale) => _editorOnly(locale);

  @override
  Future<MaterialLocalizations> load(Locale locale) =>
      DefaultMaterialLocalizations.load(locale);

  @override
  bool shouldReload(_FallbackMaterialDelegate old) => false;
}

class _FallbackCupertinoDelegate
    extends LocalizationsDelegate<CupertinoLocalizations> {
  const _FallbackCupertinoDelegate();

  @override
  bool isSupported(Locale locale) => _editorOnly(locale);

  @override
  Future<CupertinoLocalizations> load(Locale locale) =>
      DefaultCupertinoLocalizations.load(locale);

  @override
  bool shouldReload(_FallbackCupertinoDelegate old) => false;
}

class _FallbackWidgetsDelegate
    extends LocalizationsDelegate<WidgetsLocalizations> {
  const _FallbackWidgetsDelegate();

  @override
  bool isSupported(Locale locale) => _editorOnly(locale);

  @override
  Future<WidgetsLocalizations> load(Locale locale) =>
      SynchronousFuture<WidgetsLocalizations>(
          _rtlLanguages.contains(locale.languageCode)
              ? const _RtlWidgetsLocalizations()
              : const DefaultWidgetsLocalizations());

  @override
  bool shouldReload(_FallbackWidgetsDelegate old) => false;
}

/// The English widgets strings, laid out right to left.
class _RtlWidgetsLocalizations extends DefaultWidgetsLocalizations {
  const _RtlWidgetsLocalizations();

  @override
  TextDirection get textDirection => TextDirection.rtl;
}
